import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from '../components/navigation/navigation';
import dynamic from 'next/dynamic';
import Particles from "@/components/background/particles";
// const ThreeScene = dynamic(() => import('../components/threejs/ThreeScene'));

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black flex justify-center p-2`}
      >
      <Navigation />
      {/* <ThreeScene /> */}
      <Particles
        className="fixed inset-0 -z-10 animate-fade-in"
        quantity={100}
      />
      <div className="fixed inset-0 -z-10 flex flex-col overflow-hidden bg-gradient-to-tl from-black via-zinc-600/20 to-black">
      </div>
        {children}
      </body>
    </html>
  );
}
